/*
 * Generated by ./misc/optlib2c from optlib/dosbatch.ctags, Don't edit this manually.
 */
#include "general.h"
#include "parse.h"
#include "routines.h"
#include "field.h"
#include "xtag.h"
#include "selectors.h"


static void initializeDosBatchParser (const langType language CTAGS_ATTR_UNUSED)
{
}

extern parserDefinition* DosBatchParser (void)
{
	static const char *const extensions [] = {
		"bat",
		"cmd",
		NULL
	};

	static const char *const aliases [] = {
		NULL
	};

	static const char *const patterns [] = {
		NULL
	};

	static kindDefinition DosBatchKindTable [] = {
		{
		  true, 'l', "label", "labels",
		},
		{
		  true, 'v', "variable", "variables",
		},
	};
	static tagRegexTable DosBatchTagRegexTable [] = {
		{"^:([A-Za-z_0-9]+)", "\\1",
		"l", NULL, NULL, false},
		{"set[ \t]+([A-Za-z_0-9]+)[ \t]*=", "\\1",
		"v", "{icase}", NULL, false},
	};

	static selectLanguage selectors[] = { selectByRexxCommentAndDosbatchLabelPrefix, NULL };

	parserDefinition* const def = parserNew ("DosBatch");

	def->versionCurrent= 0;
	def->versionAge    = 0;
	def->enabled       = true;
	def->extensions    = extensions;
	def->patterns      = patterns;
	def->aliases       = aliases;
	def->selectLanguage= selectors;
	def->method        = METHOD_NOT_CRAFTED|METHOD_REGEX;
	def->kindTable     = DosBatchKindTable;
	def->kindCount     = ARRAY_SIZE(DosBatchKindTable);
	def->tagRegexTable = DosBatchTagRegexTable;
	def->tagRegexCount = ARRAY_SIZE(DosBatchTagRegexTable);
	def->initialize    = initializeDosBatchParser;

	return def;
}
