name: Create a weekly tag

on:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - run: misc/git-tag-maybe.sh
